{
  "initials": [
    {
      "above_threshold": 10,
      "pin": "1234"
    },
    {
      "name": "mikhail",
      "pin": "1234",
      "funds": 10000
    }
  ],
  "vote_start": 9,
  "vote_tally": 87,
  "tally_end": 93,
  "proposals": 134,
  "challenges": 3,
  "slot_duration": 20,
  "slots_per_epoch": 45,
  "voting_power": 8000,
  "fund_name": "Fund 3",
  "private": false,
  "fund_id":20,
  "linear_fees": {
    "constant": 0,
    "coefficient": 0,
    "certificate": 0
  },
  "consensus_leader_ids": [
    "ed25519_pk1lv8m52aakjm2z0yqtltqxp6f9kemtcmt9ej7gn86eru7gpt8tn0q08j8lt",
    "ed25519_pk1qvq6prs87lmg6aeurdhq93fhtrx034yzc3jgj6lc3xc3a8lff98qtgw4dw",
    "ed25519_pk1g0mftq89wpwaymtegmuppyxtfnsp4jcc42cwcz4p6flvd7c5zn4qm3lmtp"
  ]
}