version: 2.1

executors:
  rust-stable:
    docker:
      - image: cimg/rust:1.53.0-node
    working_directory: /home/circleci/build
    resource_class: xlarge

jobs:
  vitup_test:
    description: "Steps for the vitup unit test jobs"
    docker:
      - image: cimg/rust:1.53.0-node
    parameters:
      mode:
        type: string
        default: ''
      cargo_behavior:
        type: string
        default: --verbose
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: install build reqs
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install build-essential libssl-dev pkg-config    
      - run:
          name: checkout jormungandr
          command: |
            git clone https://github.com/input-output-hk/jormungandr.git
            cd jormungandr
            git checkout 9f328ec8f1595039cb728228233fca4d5b1059f0
      - run:
          name: install jormungandr
          command: |
            cd jormungandr
            cargo install --path jormungandr --locked
            cargo install --path jcli --locked
      - run:
          name: checkout vit-station-service
          command: |
            git clone https://github.com/input-output-hk/vit-servicing-station.git
            cd vit-servicing-station
            git checkout df9490ae33bb3abef8cb6877001091b179c5d38b
      - run:
          name: install vit-station-service
          command: |
            cd vit-servicing-station
            cargo install --path vit-servicing-station-server --locked
      - run:
          name: install iapyx utils
          command: |
            cargo install --path iapyx --locked                  
      - run:
          name: Run tests
          no_output_timeout: 60m
          environment:
            RUST_BACKTRACE: 1
          command: |
            cd vitup
            cargo test --release -- --test-threads=1

  test_debug:
    executor: rust-stable
    environment:
      RUSTFLAGS: -D warnings
      CARGO_INCREMENTAL: 0
    steps:
      - test

commands:
  test:
    description: "Steps for the test jobs"
    parameters:
      mode:
        type: string
        default: ''
      cargo_behavior:
        type: string
        default: --verbose
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install build reqs
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install build-essential libssl-dev pkg-config    
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: install build reqs
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install build-essential libssl-dev pkg-config    
      - run:
          name: checkout jormungandr
          command: |
            git clone https://github.com/input-output-hk/jormungandr.git
            cd jormungandr
            git checkout b2b27dfd7e2dd9253c103e92df2ae86f159d06f7
      - run:
          name: install jormungandr
          command: |
            cd jormungandr
            cargo install --path jormungandr --locked
            cargo install --path jcli --locked
      - run:
          name: checkout vit-station-service
          command: |
            git clone https://github.com/input-output-hk/vit-servicing-station.git
            cd vit-servicing-station
            git checkout df9490ae33bb3abef8cb6877001091b179c5d38b
      - run:
          name: install vit-station-service
          command: |
            cd vit-servicing-station
            cargo install --path vit-servicing-station-server --locked
      - run:
          name: install iapyx utils
          command: |
            cargo install --path iapyx --locked
      - run:
          name: Run tests
          no_output_timeout: 60m
          environment:
            RUST_BACKTRACE: 1
          command: |
            cargo test --release -- --test-threads=1
workflows:
  version: 2
  test_all:
    jobs:
      - test_debug
      - vitup_test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
            filters:
              branches:
                only:
                - main