{  
  "initials": [
    {
      "above_threshold": 5000,
      "pin": "1234"
    }
  ],
  "vote_start": 0,
  "vote_tally": 71,
  "tally_end": 81,
  "refresh_time": "2021-04-16T09:00:00",
  "next_vote_start_time": "2021-04-30T21:00:00",
  "proposals": 285,
  "challenges": 7,
  "slot_duration": 20,
  "slots_per_epoch": 180,
  "voting_power": 450,
  "fund_name": "Fund4",
  "private": false,
  "fund_id":42,
  "linear_fees": {
    "constant": 0,
    "coefficient": 0,
    "certificate": 0
  },
  "consensus_leader_ids": [
    "ed25519_pk1e8u3mmtqe725q3ytw6a7xqnayudx54etecq6zhtwdd73usnrn0rqzznvd3",
    "ed25519_pk17dkw8qqm9guzxvf9mlyl6wr0e7l52lulagmywvun79lmyq5dkm3s29h8a6",
    "ed25519_pk1mpf8dnt3xukjv2prywf7nlxznyytrr797za2fm55e6lsdcx8ys0sv8js9g"
  ],
  "version":"0.1"
}