{  
  "initials": [
    {
      "above_threshold": 10,
      "pin": "1234"
    }
  ],
  "vote_start": 0,
  "vote_tally": 701,
  "tally_end": 801,
  "refresh_time": "2021-04-16T09:00:00",
  "next_vote_start_time": "2021-04-30T21:00:00",
  "proposals": 285,
  "challenges": 7,
  "slot_duration": 20,
  "slots_per_epoch": 180,
  "voting_power": 450,
  "fund_name": "Fund4",
  "private": false,
  "fund_id":1,
  "linear_fees": {
    "constant": 0,
    "coefficient": 0,
    "certificate": 0
  },
  "consensus_leader_ids": [
    "ed25519_pk1u6g7nps2wu9ec7sruzpnn3wg4pzh3wxrxazm759u9fcetzlqcufspuv82c",
    "ed25519_pk12jcknkxjehms8zacl9hl0ucg86hsvtd4u8qpjh0qjle5czvwnegs46flpf",
    "ed25519_pk18t33p8x76aqrjkdk5cgtw7nkkmp4tpg0hwnawrx4dl3lkxt3hvfq02pjpl"
  ],
  "version":"2.0"
}

