[package]
name = "vitup"
version = "0.0.1"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_debug = "0.5"
dialoguer = "0.7.1"
error-chain = "0.12"
assert_fs = "1.0"
glob = "0.3.0"
walkdir = "2.3.1"
chain-core           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-crypto         = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-addr           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-time           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-vote           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
jormungandr-scenario-tests = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "1955f6a1a60bc66635cdd67460872ff7e4c29022" } 
jormungandr-testing-utils = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "1955f6a1a60bc66635cdd67460872ff7e4c29022" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "1955f6a1a60bc66635cdd67460872ff7e4c29022" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch = "master" }
vit-servicing-station-tests = { git = "https://github.com/input-output-hk/vit-servicing-station.git", rev = "3e15e560a7ff57c793f3c156c19e235d84934cd7" }
vit-servicing-station-lib = { git = "https://github.com/input-output-hk/vit-servicing-station.git", rev = "3e15e560a7ff57c793f3c156c19e235d84934cd7" }
iapyx = { path = "../iapyx" }
poldercast = { git = "https://github.com/primetype/poldercast.git", rev = "8305f1560392a9d26673ca996e7646c8834533ef" }
rand = "0.7"
rand_core = "0.5"
rand_chacha = "0.2"
function_name = "0.2.0"
chrono = "0.4"
regex = "1.4"
structopt = "0.3"
thiserror = "1.0"
warp-reverse-proxy = "0.3.1"
hex = "0.4"
futures = "0.3.8"
console = "0.13"
indicatif = "0.15"
lazy_static = "1"
serde_json = "1.0"
serde_yaml = "0.8"
yaml-rust = "0.4.4"
serde = { version="=1.0.118", features = ["derive"] }
warp = "0.3"
tokio = { version = "1.1", features = ["macros","rt","rt-multi-thread"] }
json = "0.12.4"
image = "0.23.12"
base64 = "0.12.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
tracing-subscriber = "0.2.16"
tracing = "0.1"
tracing-appender = "0.1.2"

[dependencies.reqwest]
version = "0.10.10"
default-features = false
features = ["blocking", "rustls-tls"]
