[package]
name = "registration-service"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde","v4"] }
chrono = "0.4"
walkdir = "2.3.1"
structopt = "0.3"
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", rev="919e6e99ef064b9e810887bf72d961281ae2dd49" }
jormungandr-integration-tests = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "91d6ffc15122f0b18e8e8a4d6e1454dcc99b54da" } 
futures = "0.3.8"
serde = { version="=1.0.118", features = ["derive"] }
warp = "0.3"
thiserror = "1.0"
tokio = { version = "1.2", features = ["macros","rt","process"] }
serde_json = "1.0"
serde_yaml = "0.8"

[dependencies.reqwest]
version = "0.10.10"
default-features = false
features = ["blocking", "rustls-tls"]
