[package]
name = "integration-tests"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jormungandr-scenario-tests = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "18de926dc7f26c6b7ab28f2131c76df5369ff2b4" } 
jormungandr-testing-utils = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "18de926dc7f26c6b7ab28f2131c76df5369ff2b4" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "18de926dc7f26c6b7ab28f2131c76df5369ff2b4" }
vit-servicing-station-tests = { git = "https://github.com/input-output-hk/vit-servicing-station.git", rev = "5c545145036d3c117ac5e0cf9ea0c7a90acd256a" }
vit-servicing-station-lib = { git = "https://github.com/input-output-hk/vit-servicing-station.git", rev = "5c545145036d3c117ac5e0cf9ea0c7a90acd256a" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch="master" }
vitup = { path = "../vitup"} 
iapyx = { path = "../iapyx"} 
snapshot-trigger-service = { path = "../snapshot-trigger-service" }
rand_chacha = "0.2"
tokio = { version = "1.1", features = ["macros","rt","rt-multi-thread"] }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
thiserror = "1.0"
rand = "0.8"
cfg-if = "1.0.0"
assert_fs = "1.0"
chrono = "0.4.19"

[features]
load-tests = []
soak-tests = []