[package]
name = "integration-tests"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jormungandr-scenario-tests = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "3ae714a976bd645eb9a66ef7213cd983673a1ce8" } 
jormungandr-integration-tests = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "3ae714a976bd645eb9a66ef7213cd983673a1ce8" } 
jormungandr-testing-utils = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "3ae714a976bd645eb9a66ef7213cd983673a1ce8" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git",  rev = "3ae714a976bd645eb9a66ef7213cd983673a1ce8" }
vit-servicing-station-tests = { git = "https://github.com/input-output-hk/vit-servicing-station.git", rev = "df9490ae33bb3abef8cb6877001091b179c5d38b" }
vit-servicing-station-lib = { git = "https://github.com/input-output-hk/vit-servicing-station.git", rev = "df9490ae33bb3abef8cb6877001091b179c5d38b" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch="master" }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
vitup = { path = "../vitup"} 
iapyx = { path = "../iapyx"} 
snapshot-trigger-service = { path = "../snapshot-trigger-service" }
registration-service = { path = "../registration-service" }
rand_chacha = "0.2"
tokio = { version = "1.1", features = ["macros","rt","rt-multi-thread"] }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
thiserror = "1.0"
rand = "0.8"
libmath = "0.2.1"
cfg-if = "1.0.0"
assert_fs = "1.0"
chrono = "0.4.19"

[features]
load-tests = []
soak-tests = []